[2025-04-23T12:42:00.028+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-23T12:42:00.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T12:41:58.122911+00:00 [queued]>
[2025-04-23T12:42:00.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T12:41:58.122911+00:00 [queued]>
[2025-04-23T12:42:00.044+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-23T12:42:00.057+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_preprocessing> on 2025-04-23 12:41:58.122911+00:00
[2025-04-23T12:42:00.064+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=219) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T12:42:00.065+0000] {standard_task_runner.py:63} INFO - Started process 221 to run task
[2025-04-23T12:42:00.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_pipeline', 'run_preprocessing', 'manual__2025-04-23T12:41:58.122911+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocessing.py', '--cfg-path', '/tmp/tmpxjf_fzky']
[2025-04-23T12:42:00.066+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask run_preprocessing
[2025-04-23T12:42:00.091+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T12:41:58.122911+00:00 [running]> on host 73223bf8df73
[2025-04-23T12:42:00.134+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocessing_pipeline' AIRFLOW_CTX_TASK_ID='run_preprocessing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T12:41:58.122911+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T12:41:58.122911+00:00'
[2025-04-23T12:42:00.135+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-23T12:42:00.135+0000] {dag_preprocessing.py:105} INFO - Esecuzione del task di preprocessing iniziata.
[2025-04-23T12:42:00.136+0000] {dag_preprocessing.py:36} INFO - Avvio del preprocessing dei dati...
[2025-04-23T12:42:00.136+0000] {dag_preprocessing.py:21} INFO - Inizializzazione di NLTK...
[2025-04-23T12:42:00.136+0000] {dag_preprocessing.py:26} INFO - Scaricamento 'punkt'...
[2025-04-23T12:42:00.450+0000] {dag_preprocessing.py:26} INFO - Scaricamento 'stopwords'...
[2025-04-23T12:42:00.452+0000] {dag_preprocessing.py:26} INFO - Scaricamento 'wordnet'...
[2025-04-23T12:42:00.483+0000] {dag_preprocessing.py:30} INFO - Risorse NLTK scaricate correttamente.
[2025-04-23T12:42:00.484+0000] {dag_preprocessing.py:40} INFO - Percorso previsto per il CSV: /opt/***/sentiment_data/all-data.csv
[2025-04-23T12:42:00.484+0000] {dag_preprocessing.py:43} INFO - Caricamento del file CSV...
[2025-04-23T12:42:00.507+0000] {dag_preprocessing.py:45} INFO - File CSV caricato correttamente, numero di righe: 4846
[2025-04-23T12:42:00.509+0000] {dag_preprocessing.py:54} INFO - Strumenti di preprocessamento inizializzati.
[2025-04-23T12:42:00.509+0000] {dag_preprocessing.py:80} INFO - Inizio preprocessamento del testo...
[2025-04-23T12:42:00.511+0000] {dag_preprocessing.py:84} ERROR - Errore durante il preprocessamento: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/opt/***/nltk_data'
**********************************************************************

[2025-04-23T12:42:00.511+0000] {dag_preprocessing.py:110} ERROR - Errore nel task di preprocessing: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/opt/***/nltk_data'
**********************************************************************

[2025-04-23T12:42:00.512+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-23T12:42:00.512+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-23T12:42:00.518+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=preprocessing_pipeline, task_id=run_preprocessing, run_id=manual__2025-04-23T12:41:58.122911+00:00, execution_date=20250423T124158, start_date=20250423T124200, end_date=20250423T124200
[2025-04-23T12:42:00.555+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-23T12:42:00.565+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T12:42:00.566+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
