[2025-04-19T10:17:54.088+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-19T10:17:54.099+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-19T10:17:47.412033+00:00 [queued]>
[2025-04-19T10:17:54.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-19T10:17:47.412033+00:00 [queued]>
[2025-04-19T10:17:54.102+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-19T10:17:54.108+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_preprocessing> on 2025-04-19 10:17:47.412033+00:00
[2025-04-19T10:17:54.113+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=87) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-19T10:17:54.114+0000] {standard_task_runner.py:63} INFO - Started process 96 to run task
[2025-04-19T10:17:54.115+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_pipeline', 'run_preprocessing', 'manual__2025-04-19T10:17:47.412033+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocessing.py', '--cfg-path', '/tmp/tmp8m1m9kfo']
[2025-04-19T10:17:54.115+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask run_preprocessing
[2025-04-19T10:17:54.139+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-19T10:17:47.412033+00:00 [running]> on host 75bccde60ebb
[2025-04-19T10:17:54.193+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocessing_pipeline' AIRFLOW_CTX_TASK_ID='run_preprocessing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T10:17:47.412033+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-19T10:17:47.412033+00:00'
[2025-04-19T10:17:54.194+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-19T10:17:54.197+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-19T10:17:54.198+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_preprocessing.py", line 17, in preprocess
    df = pd.read_csv("/opt/airflow/sentiment_data/all-data.csv", encoding='latin1', names=['label', 'text'])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/sentiment_data/all-data.csv'
[2025-04-19T10:17:54.204+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocessing_pipeline, task_id=run_preprocessing, run_id=manual__2025-04-19T10:17:47.412033+00:00, execution_date=20250419T101747, start_date=20250419T101754, end_date=20250419T101754
[2025-04-19T10:17:54.210+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task run_preprocessing ([Errno 2] No such file or directory: '/opt/airflow/sentiment_data/all-data.csv'; 96)
[2025-04-19T10:17:54.215+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-19T10:17:54.223+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-19T10:17:54.224+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
